development:
  adapter: postgresql
  encoding: unicode
  database: wine_notes_development
  pool: 5
  username: rails_dev
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wine_notes_test
  pool: 5
  username: rails_dev
  password:


production:
  adapter: postgresql
  encoding: unicode
  database: wine_notes_production
  pool: 5
  username: rails_dev
  password:
